# Подключаем стандартные типы (html, css, js, png и т.д.)
include /etc/nginx/mime.types;

server {
    listen 80;
    server_name localhost;
    
    # Устанавливаем тип по умолчанию только если файл не распознан
    default_type application/octet-stream;

    root /usr/share/nginx/html;
    index index.html;


    # Добавляем ТОЛЬКО то, чего нет в стандартном файле (3D модели)
    types {
        model/gltf-binary glb;
        model/gltf+json gltf;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /api/ {
        proxy_pass http://backend:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        
        proxy_connect_timeout 60s;
        proxy_send_timeout 60s;
        proxy_read_timeout 60s;
    }

    location /admin/ {
        proxy_pass http://backend:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}