server {
    listen 80;
    server_name localhost;

    default_type application/octet-stream;

    root /usr/share/nginx/html;
    index index.html;

    types {
        text/html html htm;
        application/javascript js mjs;
        text/css css;
        model/gltf-binary glb;
        model/gltf+json gltf;
        image/svg+xml svg;
        image/png png;
        image/jpeg jpg jpeg;
        image/gif gif;
        image/webp webp;
        font/woff2 woff2;
        font/woff woff;
        font/ttf ttf;
        application/json json;
    }


    location / {
        try_files $uri $uri/ /index.html;
    }

    location /api/ {
        proxy_pass http://backend:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_connect_timeout 60s;
        proxy_send_timeout 60s;
        proxy_read_timeout 60s;
    }

    location /admin/ {
        proxy_pass http://backend:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location ~ ^(/lessons/)?undefined/media/ {
        alias /var/www/media/;
        expires 30d;
        add_header Cache-Control "public, no-transform";
    }

    location /media/ {
        alias /var/www/media/;
        expires 30d;
        add_header Cache-Control "public, no-transform";
    }
}