# Generated by Django 5.2.11 on 2026-05-14 21:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userquizprogress',
            name='max_score',
        ),
        migrations.AddField(
            model_name='quizzes',
            name='max_score',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='userquizprogress',
            name='attempt_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='userquizprogress',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='answertype',
            name='type',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='complexity',
            name='complexity',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='roles',
            name='role_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='status',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userquizprogress',
            name='id_quiz',
            field=models.ForeignKey(blank=True, db_column='id_quiz', null=True, on_delete=django.db.models.deletion.CASCADE, to='lessons.quizzes'),
        ),
        migrations.AlterField(
            model_name='userquizprogress',
            name='id_user',
            field=models.ForeignKey(blank=True, db_column='id_user', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userquizprogress',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
