# Generated by Django 5.2.11 on 2026-05-15 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_remove_userquizprogress_max_score_quizzes_max_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userquizprogress',
            name='correct_answers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userquizprogress',
            name='max_score',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='userquizprogress',
            name='status',
            field=models.CharField(choices=[('in_progress', 'В процессе'), ('completed', 'Завершен')], default='in_progress', max_length=20),
        ),
        migrations.AddField(
            model_name='userquizprogress',
            name='wrong_answers',
            field=models.IntegerField(default=0),
        ),
    ]
