BEGIN;
--
-- Create model AnswerType
--
CREATE TABLE "answer_type" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "type" varchar NULL);
--
-- Create model Complexity
--
CREATE TABLE "complexity" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "complexity" varchar NULL);
--
-- Create model Roles
--
CREATE TABLE "roles" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "role_name" varchar NULL);
--
-- Create model Status
--
CREATE TABLE "status" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "status" varchar NULL);
--
-- Create model Lessons
--
CREATE TABLE "lessons" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "task_indexs" integer NULL, "title" text NULL, "description" text NULL, "video_url" text NULL, "task_complexity" bigint NULL);
--
-- Create model Quizzes
--
CREATE TABLE "quizzes" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "title" text NULL, "id_lesson" bigint NULL);
--
-- Create model QuizzQuestions
--
CREATE TABLE "quizz_questions" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "question_text" text NULL, "id_quiz" bigint NULL);
--
-- Create model QuestionAnswers
--
CREATE TABLE "question_answers" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "answer_text" text NULL, "is_correct" bigint NULL, "id_quiz_questions" bigint NULL);
--
-- Create model Users
--
CREATE TABLE "users" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "password" varchar(128) NOT NULL, "last_login" timestamp with time zone NULL, "is_superuser" boolean NOT NULL, "username" varchar(150) NOT NULL UNIQUE, "first_name" varchar(150) NOT NULL, "last_name" varchar(150) NOT NULL, "is_staff" boolean NOT NULL, "is_active" boolean NOT NULL, "date_joined" timestamp with time zone NOT NULL, "email" varchar(254) NOT NULL UNIQUE, "role_id" bigint NULL);
CREATE TABLE "users_groups" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "users_id" bigint NOT NULL, "group_id" integer NOT NULL);
CREATE TABLE "users_user_permissions" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "users_id" bigint NOT NULL, "permission_id" integer NOT NULL);
--
-- Create model UserLessonProgress
--
CREATE TABLE "user_lesson_progress" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "id_lesson" bigint NULL, "id_user" bigint NULL, "status" bigint NULL);
--
-- Create model UserQuizProgress
--
CREATE TABLE "user_quiz_progress" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "max_score" integer NOT NULL, "score" integer NOT NULL, "id_quiz" bigint NULL, "id_user" bigint NULL);
ALTER TABLE "lessons" ADD CONSTRAINT "lessons_task_complexity_28604db0_fk_complexity_id" FOREIGN KEY ("task_complexity") REFERENCES "complexity" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "lessons_task_complexity_28604db0" ON "lessons" ("task_complexity");
ALTER TABLE "quizzes" ADD CONSTRAINT "quizzes_id_lesson_6cda1a68_fk_lessons_id" FOREIGN KEY ("id_lesson") REFERENCES "lessons" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "quizzes_id_lesson_6cda1a68" ON "quizzes" ("id_lesson");
ALTER TABLE "quizz_questions" ADD CONSTRAINT "quizz_questions_id_quiz_89f44de2_fk_quizzes_id" FOREIGN KEY ("id_quiz") REFERENCES "quizzes" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "quizz_questions_id_quiz_89f44de2" ON "quizz_questions" ("id_quiz");
ALTER TABLE "question_answers" ADD CONSTRAINT "question_answers_is_correct_210c90dc_fk_answer_type_id" FOREIGN KEY ("is_correct") REFERENCES "answer_type" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "question_answers" ADD CONSTRAINT "question_answers_id_quiz_questions_447fe2a0_fk_quizz_que" FOREIGN KEY ("id_quiz_questions") REFERENCES "quizz_questions" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "question_answers_is_correct_210c90dc" ON "question_answers" ("is_correct");
CREATE INDEX "question_answers_id_quiz_questions_447fe2a0" ON "question_answers" ("id_quiz_questions");
ALTER TABLE "users" ADD CONSTRAINT "users_role_id_1900a745_fk_roles_id" FOREIGN KEY ("role_id") REFERENCES "roles" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "users_username_e8658fc8_like" ON "users" ("username" varchar_pattern_ops);
CREATE INDEX "users_email_0ea73cca_like" ON "users" ("email" varchar_pattern_ops);
CREATE INDEX "users_role_id_1900a745" ON "users" ("role_id");
ALTER TABLE "users_groups" ADD CONSTRAINT "users_groups_users_id_group_id_83a49e68_uniq" UNIQUE ("users_id", "group_id");
ALTER TABLE "users_groups" ADD CONSTRAINT "users_groups_users_id_1e682706_fk_users_id" FOREIGN KEY ("users_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "users_groups" ADD CONSTRAINT "users_groups_group_id_2f3517aa_fk_auth_group_id" FOREIGN KEY ("group_id") REFERENCES "auth_group" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "users_groups_users_id_1e682706" ON "users_groups" ("users_id");
CREATE INDEX "users_groups_group_id_2f3517aa" ON "users_groups" ("group_id");
ALTER TABLE "users_user_permissions" ADD CONSTRAINT "users_user_permissions_users_id_permission_id_d7a00931_uniq" UNIQUE ("users_id", "permission_id");
ALTER TABLE "users_user_permissions" ADD CONSTRAINT "users_user_permissions_users_id_e1ed60a2_fk_users_id" FOREIGN KEY ("users_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "users_user_permissions" ADD CONSTRAINT "users_user_permissio_permission_id_6d08dcd2_fk_auth_perm" FOREIGN KEY ("permission_id") REFERENCES "auth_permission" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "users_user_permissions_users_id_e1ed60a2" ON "users_user_permissions" ("users_id");
CREATE INDEX "users_user_permissions_permission_id_6d08dcd2" ON "users_user_permissions" ("permission_id");
ALTER TABLE "user_lesson_progress" ADD CONSTRAINT "user_lesson_progress_id_lesson_2aa5b52e_fk_lessons_id" FOREIGN KEY ("id_lesson") REFERENCES "lessons" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "user_lesson_progress" ADD CONSTRAINT "user_lesson_progress_id_user_5a12d964_fk_users_id" FOREIGN KEY ("id_user") REFERENCES "users" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "user_lesson_progress" ADD CONSTRAINT "user_lesson_progress_status_d5bad959_fk_status_id" FOREIGN KEY ("status") REFERENCES "status" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "user_lesson_progress_id_lesson_2aa5b52e" ON "user_lesson_progress" ("id_lesson");
CREATE INDEX "user_lesson_progress_id_user_5a12d964" ON "user_lesson_progress" ("id_user");
CREATE INDEX "user_lesson_progress_status_d5bad959" ON "user_lesson_progress" ("status");
ALTER TABLE "user_quiz_progress" ADD CONSTRAINT "user_quiz_progress_id_quiz_53138cf7_fk_quizzes_id" FOREIGN KEY ("id_quiz") REFERENCES "quizzes" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "user_quiz_progress" ADD CONSTRAINT "user_quiz_progress_id_user_3012b8a8_fk_users_id" FOREIGN KEY ("id_user") REFERENCES "users" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "user_quiz_progress_id_quiz_53138cf7" ON "user_quiz_progress" ("id_quiz");
CREATE INDEX "user_quiz_progress_id_user_3012b8a8" ON "user_quiz_progress" ("id_user");
COMMIT;
